name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  push:
    branches:
      - github-actions

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
#      - name: Run the Maven build
#        run: mvn clean install

      - name: Testing commit
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: update build version
        run: mvn build-helper:parse-version versions:set@patch

      - name: Commit back to branch
        run: |
          git add -A
          git commit -m "Testing version upgrade"
          git push
      - run: echo "ğŸ This job's status is ${{ job.status }}."
